### ISSUE TITLE
can't use on raspberrypi:(

### ISSUE THREAD

**Issue by ranma1988** [mosquito/python-systemd#8]
$ pip3 install systemd

    error in systemd setup command: Invalid environment marker: python_version < "3.3"

$ pip3 --version
pip 1.5.6 from /usr/lib/python3/dist-packages (python 3.4)

**Comment by troyfontaine** [comment]
@ranma1988 It looks like this is related to using an older version of python 2.7 (in my case, it was Python 2.7.9 with Virtualenv 15.1).  I jumped through some hoops to install a newer version of Setuptools and Pip, then installed Virtualenv 16.0 and got Python 2.7.13. Now systemd installs without issue.

**Comment by mosquito** [comment]
@ranma1988 I guess virtualenv is excellent solution for this issue. It's looks like the setuptools is too old.
